In [169]:
from pandas import read_json

dataset = read_json("/workspaces/Main-DSDT-Example-Repo/Data Science/NoSQL Database Folder/products.json")

In [170]:
# dataset['tags'][2] = 'bestseller'

In [171]:
display(dataset)

,_id,name,price,category,tags,discontinued
0,p0,Total systemic project,131.73,Toys,"[sale, limited, eco]",NaN
1,p1,Compatible real-time productivity,174.51,Outdoors,"[eco, bestseller, new]",NaN
2,p2,Down-sized national superstructure,153.88,Electronics,[],NaN
3,p3,Fully-configurable cohesive Local Area Network,75.00,Books,"[new, limited]",NaN
4,p4,Multi-tiered encompassing productivity,194.76,Home,[],NaN
5,p5,Team-oriented next generation definition,166.73,Toys,"[bestseller, sale]",NaN
6,p6,Synergized fresh-thinking throughput,13.94,Outdoors,"[new, sale]",1.0
7,p7,Vision-oriented analyzing emulation,79.12,Home,"[sale, eco]",NaN
8,p8,Automated foreground initiative,135.68,Electronics,[bestseller],NaN
9,p9,Future-proofed asymmetric data-warehouse,36.86,Home,"[bestseller, sale]",NaN
10,p10,Re-contextualized transitional functionalities,169.36,Electronics,[new],1.0
11,p11,Extended solution-oriented methodology,83.23,Electronics,[bestseller],1.0
12,p12,Object-based secondary knowledgebase,66.36,Home,"[limited, sale, bestseller]",NaN
13,p13,Digitized empowering challenge,150.27,Toys,"[bestseller, limited]",1.0
14,p14,Fully-configurable value-added open architecture,82.88,Outdoors,[bestseller],NaN

In [172]:
column = dataset['tags']

display(column)

0            [sale, limited, eco]
1          [eco, bestseller, new]
2                              []
3                  [new, limited]
4                              []
5              [bestseller, sale]
6                     [new, sale]
7                     [sale, eco]
8                    [bestseller]
9              [bestseller, sale]
10                          [new]
11                   [bestseller]
12    [limited, sale, bestseller]
13          [bestseller, limited]
14                   [bestseller]
Name: tags, dtype: object

In [173]:
['bestseller', 'sale']

{0:'bestseller', 1:'sale', }

{0: 'bestseller', 1: 'sale'}

In [174]:
dictified_column = column.copy()

from numpy import isscalar

for index, element in enumerate(column):
    if isscalar(element):
        dictified_element = {0:element}
        dictified_column[index] = dictified_element
    if type(element) == list:
        enumerated_element = enumerate(element)
        dictified_element = dict(enumerated_element)
        dictified_column[index] = dictified_element

In [175]:
dictified_column

0            {0: 'sale', 1: 'limited', 2: 'eco'}
1          {0: 'eco', 1: 'bestseller', 2: 'new'}
2                                             {}
3                       {0: 'new', 1: 'limited'}
4                                             {}
5                   {0: 'bestseller', 1: 'sale'}
6                          {0: 'new', 1: 'sale'}
7                          {0: 'sale', 1: 'eco'}
8                              {0: 'bestseller'}
9                   {0: 'bestseller', 1: 'sale'}
10                                    {0: 'new'}
11                             {0: 'bestseller'}
12    {0: 'limited', 1: 'sale', 2: 'bestseller'}
13               {0: 'bestseller', 1: 'limited'}
14                             {0: 'bestseller'}
Name: tags, dtype: object

In [176]:
from pandas import json_normalize
flattened_subframe = json_normalize(dictified_column).add_prefix('tags.')

In [177]:
flattened_subframe

        tags.0      tags.1      tags.2
0         sale     limited         eco
1          eco  bestseller         new
2          NaN         NaN         NaN
3          new     limited         NaN
4          NaN         NaN         NaN
5   bestseller        sale         NaN
6          new        sale         NaN
7         sale         eco         NaN
8   bestseller         NaN         NaN
9   bestseller        sale         NaN
10         new         NaN         NaN
11  bestseller         NaN         NaN
12     limited        sale  bestseller
13  bestseller     limited         NaN
14  bestseller         NaN         NaN

In [178]:
columns_of_fsf = flattened_subframe.columns
dataset[columns_of_fsf] = flattened_subframe

dataset

,_id,name,price,category,tags,discontinued,tags.0,tags.1,tags.2
0,p0,Total systemic project,131.73,Toys,"[sale, limited, eco]",NaN,sale,limited,eco
1,p1,Compatible real-time productivity,174.51,Outdoors,"[eco, bestseller, new]",NaN,eco,bestseller,new
2,p2,Down-sized national superstructure,153.88,Electronics,[],NaN,NaN,NaN,NaN
3,p3,Fully-configurable cohesive Local Area Network,75.00,Books,"[new, limited]",NaN,new,limited,NaN
4,p4,Multi-tiered encompassing productivity,194.76,Home,[],NaN,NaN,NaN,NaN
5,p5,Team-oriented next generation definition,166.73,Toys,"[bestseller, sale]",NaN,bestseller,sale,NaN
6,p6,Synergized fresh-thinking throughput,13.94,Outdoors,"[new, sale]",1.0,new,sale,NaN
7,p7,Vision-oriented analyzing emulation,79.12,Home,"[sale, eco]",NaN,sale,eco,NaN
8,p8,Automated foreground initiative,135.68,Electronics,[bestseller],NaN,bestseller,NaN,NaN
9,p9,Future-proofed asymmetric data-warehouse,36.86,Home,"[bestseller, sale]",NaN,bestseller,sale,NaN
10,p10,Re-contextualized transitional functionalities,169.36,Electronics,[new],1.0,new,NaN,NaN
11,p11,Extended solution-oriented methodology,83.23,Electronics,[bestseller],1.0,bestseller,NaN,NaN
12,p12,Object-based secondary knowledgebase,66.36,Home,"[limited, sale, bestseller]",NaN,limited,sale,bestseller
13,p13,Digitized empowering challenge,150.27,Toys,"[bestseller, limited]",1.0,bestseller,limited,NaN
14,p14,Fully-configurable value-added open architecture,82.88,Outdoors,[bestseller],NaN,bestseller,NaN,NaN

In [179]:
updated_dataset = dataset.drop(columns = ['tags', '_id'])

updated_dataset

,name,price,category,discontinued,tags.0,tags.1,tags.2
0,Total systemic project,131.73,Toys,NaN,sale,limited,eco
1,Compatible real-time productivity,174.51,Outdoors,NaN,eco,bestseller,new
2,Down-sized national superstructure,153.88,Electronics,NaN,NaN,NaN,NaN
3,Fully-configurable cohesive Local Area Network,75.00,Books,NaN,new,limited,NaN
4,Multi-tiered encompassing productivity,194.76,Home,NaN,NaN,NaN,NaN
5,Team-oriented next generation definition,166.73,Toys,NaN,bestseller,sale,NaN
6,Synergized fresh-thinking throughput,13.94,Outdoors,1.0,new,sale,NaN
7,Vision-oriented analyzing emulation,79.12,Home,NaN,sale,eco,NaN
8,Automated foreground initiative,135.68,Electronics,NaN,bestseller,NaN,NaN
9,Future-proofed asymmetric data-warehouse,36.86,Home,NaN,bestseller,sale,NaN
10,Re-contextualized transitional functionalities,169.36,Electronics,1.0,new,NaN,NaN
11,Extended solution-oriented methodology,83.23,Electronics,1.0,bestseller,NaN,NaN
12,Object-based secondary knowledgebase,66.36,Home,NaN,limited,sale,bestseller
13,Digitized empowering challenge,150.27,Toys,1.0,bestseller,limited,NaN
14,Fully-configurable value-added open architecture,82.88,Outdoors,NaN,bestseller,NaN,NaN

In [180]:
from pandas import get_dummies

ohe_dataset = get_dummies(updated_dataset)

ohe_dataset

,price,discontinued,name_Automated foreground initiative,name_Compatible real-time productivity,name_Digitized empowering challenge,name_Down-sized national superstructure,name_Extended solution-oriented methodology,name_Fully-configurable cohesive Local Area Network,name_Fully-configurable value-added open architecture,name_Future-proofed asymmetric data-warehouse,...,tags.0_limited,tags.0_new,tags.0_sale,tags.1_bestseller,tags.1_eco,tags.1_limited,tags.1_sale,tags.2_bestseller,tags.2_eco,tags.2_new
0,131.73,NaN,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,True,False
1,174.51,NaN,False,True,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True
2,153.88,NaN,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,75.00,NaN,False,False,False,False,False,True,False,False,...,False,True,False,False,False,True,False,False,False,False
4,194.76,NaN,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,166.73,NaN,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
6,13.94,1.0,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,True,False,False,False
7,79.12,NaN,False,False,False,False,False,False,False,False,...,False,False,True,False,True,False,False,False,False,False
8,135.68,NaN,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,36.86,NaN,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,True,False,False,False
10,169.36,1.0,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
11,83.23,1.0,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,66.36,NaN,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,True,True,False,False
13,150.27,1.0,False,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
14,82.88,NaN,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False

In [181]:
ohe_dataset.columns

Index(['price', 'discontinued', 'name_Automated foreground initiative',
       'name_Compatible real-time productivity',
       'name_Digitized empowering challenge',
       'name_Down-sized national superstructure',
       'name_Extended solution-oriented methodology',
       'name_Fully-configurable cohesive Local Area Network',
       'name_Fully-configurable value-added open architecture',
       'name_Future-proofed asymmetric data-warehouse',
       'name_Multi-tiered encompassing productivity',
       'name_Object-based secondary knowledgebase',
       'name_Re-contextualized transitional functionalities',
       'name_Synergized fresh-thinking throughput',
       'name_Team-oriented next generation definition',
       'name_Total systemic project',
       'name_Vision-oriented analyzing emulation', 'category_Books',
       'category_Electronics', 'category_Home', 'category_Outdoors',
       'category_Toys', 'tags.0_bestseller', 'tags.0_eco', 'tags.0_limited',
       'tags.0_new', 'tags.0_sale', 'tags.1_bestseller', 'tags.1_eco',
       'tags.1_limited', 'tags.1_sale', 'tags.2_bestseller', 'tags.2_eco',
       'tags.2_new'],
      dtype='object')

In [182]:
redundant_category_string = 'bestseller'

redundant_subframe = ohe_dataset.filter(like = redundant_category_string)



aggregated_column = redundant_subframe.any(axis = 1)


redundant_subframe['tags.bestseller'] = aggregated_column

display(redundant_subframe)


display(aggregated_column)

/tmp/ipykernel_2314/2608703561.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  redundant_subframe['tags.bestseller'] = aggregated_column

    tags.0_bestseller  tags.1_bestseller  tags.2_bestseller  tags.bestseller
0               False              False              False            False
1               False               True              False             True
2               False              False              False            False
3               False              False              False            False
4               False              False              False            False
5                True              False              False             True
6               False              False              False            False
7               False              False              False            False
8                True              False              False             True
9                True              False              False             True
10              False              False              False            False
11               True              False              False             True
12              False              False               True             True
13               True              False              False             True
14               True              False              False             True

0     False
1      True
2     False
3     False
4     False
5      True
6     False
7     False
8      True
9      True
10    False
11     True
12     True
13     True
14     True
dtype: bool